from __future__ import annotations

from typing import Any, Dict, List


DEEP_SKY_OBJECTS: List[Dict[str, Any]] = [
    {
        "id": "M31",
        "name_en": "Andromeda Galaxy",
        "name_zh": "仙女座大星系",
        "object_type": "galaxy",
        "ra_deg": 10.684708,
        "dec_deg": 41.26875,
        "magnitude": 3.44,
        "constellation": "And",
        "importance": 1,
    },
    {
        "id": "M42",
        "name_en": "Orion Nebula",
        "name_zh": "猎户座大星云",
        "object_type": "nebula",
        "ra_deg": 83.822083,
        "dec_deg": -5.391111,
        "magnitude": 4.0,
        "constellation": "Ori",
        "importance": 1,
    },
    {
        "id": "M45",
        "name_en": "Pleiades",
        "name_zh": "昴星团",
        "object_type": "open_cluster",
        "ra_deg": 56.85,
        "dec_deg": 24.1167,
        "magnitude": 1.6,
        "constellation": "Tau",
        "importance": 1,
    },
    {
        "id": "Melotte 25",
        "name_en": "Hyades",
        "name_zh": "毕星团",
        "object_type": "open_cluster",
        "ra_deg": 66.75,
        "dec_deg": 15.8667,
        "magnitude": 0.5,
        "constellation": "Tau",
        "importance": 1,
    },
    {
        "id": "M44",
        "name_en": "Beehive Cluster",
        "name_zh": "蜂巢星团",
        "object_type": "open_cluster",
        "ra_deg": 130.1,
        "dec_deg": 19.6667,
        "magnitude": 3.7,
        "constellation": "Cnc",
        "importance": 1,
    },
    {
        "id": "NGC 869/884",
        "name_en": "Double Cluster",
        "name_zh": "英仙座双星团",
        "object_type": "open_cluster",
        "ra_deg": 35.0,
        "dec_deg": 57.1333,
        "magnitude": 3.7,
        "constellation": "Per",
        "importance": 1,
    },
    {
        "id": "M13",
        "name_en": "Hercules Globular Cluster",
        "name_zh": "武仙座球状星团",
        "object_type": "globular_cluster",
        "ra_deg": 250.42125,
        "dec_deg": 36.46167,
        "magnitude": 5.8,
        "constellation": "Her",
        "importance": 1,
    },
    {
        "id": "M22",
        "name_en": "Sagittarius Cluster",
        "name_zh": "人马座球状星团",
        "object_type": "globular_cluster",
        "ra_deg": 279.1,
        "dec_deg": -23.9047,
        "magnitude": 5.1,
        "constellation": "Sgr",
        "importance": 1,
    },
    {
        "id": "M7",
        "name_en": "Ptolemy Cluster",
        "name_zh": "托勒密星团",
        "object_type": "open_cluster",
        "ra_deg": 268.4625,
        "dec_deg": -34.7933,
        "magnitude": 3.3,
        "constellation": "Sco",
        "importance": 1,
    },
    {
        "id": "M6",
        "name_en": "Butterfly Cluster",
        "name_zh": "蝴蝶星团",
        "object_type": "open_cluster",
        "ra_deg": 265.0833,
        "dec_deg": -32.2533,
        "magnitude": 4.2,
        "constellation": "Sco",
        "importance": 2,
    },
    {
        "id": "M8",
        "name_en": "Lagoon Nebula",
        "name_zh": "礁湖星云",
        "object_type": "nebula",
        "ra_deg": 270.9042,
        "dec_deg": -24.3867,
        "magnitude": 6.0,
        "constellation": "Sgr",
        "importance": 2,
    },
    {
        "id": "M20",
        "name_en": "Trifid Nebula",
        "name_zh": "三裂星云",
        "object_type": "nebula",
        "ra_deg": 270.5958,
        "dec_deg": -23.03,
        "magnitude": 6.3,
        "constellation": "Sgr",
        "importance": 2,
    },
    {
        "id": "M16",
        "name_en": "Eagle Nebula",
        "name_zh": "鹰星云",
        "object_type": "nebula",
        "ra_deg": 274.7,
        "dec_deg": -13.8167,
        "magnitude": 6.0,
        "constellation": "Ser",
        "importance": 2,
    },
    {
        "id": "M17",
        "name_en": "Omega Nebula",
        "name_zh": "欧米伽星云",
        "object_type": "nebula",
        "ra_deg": 275.1958,
        "dec_deg": -16.1717,
        "magnitude": 6.0,
        "constellation": "Sgr",
        "importance": 2,
    },
    {
        "id": "M11",
        "name_en": "Wild Duck Cluster",
        "name_zh": "野鸭星团",
        "object_type": "open_cluster",
        "ra_deg": 282.7708,
        "dec_deg": -6.27,
        "magnitude": 6.3,
        "constellation": "Sct",
        "importance": 2,
    },
    {
        "id": "M35",
        "name_en": "M35",
        "name_zh": "双子座疏散星团",
        "object_type": "open_cluster",
        "ra_deg": 92.225,
        "dec_deg": 24.3333,
        "magnitude": 5.3,
        "constellation": "Gem",
        "importance": 2,
    },
    {
        "id": "M41",
        "name_en": "M41",
        "name_zh": "大犬座疏散星团",
        "object_type": "open_cluster",
        "ra_deg": 101.5,
        "dec_deg": -20.7333,
        "magnitude": 4.5,
        "constellation": "CMa",
        "importance": 2,
    },
    {
        "id": "M4",
        "name_en": "M4",
        "name_zh": "天蝎座球状星团",
        "object_type": "globular_cluster",
        "ra_deg": 245.8958,
        "dec_deg": -26.5256,
        "magnitude": 5.6,
        "constellation": "Sco",
        "importance": 2,
    },
    {
        "id": "M5",
        "name_en": "M5",
        "name_zh": "巨蛇座球状星团",
        "object_type": "globular_cluster",
        "ra_deg": 229.6375,
        "dec_deg": 2.083,
        "magnitude": 5.7,
        "constellation": "Ser",
        "importance": 2,
    },
    {
        "id": "NGC 5139",
        "name_en": "Omega Centauri",
        "name_zh": "半人马座欧米伽星团",
        "object_type": "globular_cluster",
        "ra_deg": 201.6958,
        "dec_deg": -47.4794,
        "magnitude": 3.9,
        "constellation": "Cen",
        "importance": 1,
    },
    {
        "id": "NGC 104",
        "name_en": "47 Tucanae",
        "name_zh": "杜鹃座47",
        "object_type": "globular_cluster",
        "ra_deg": 6.0208,
        "dec_deg": -72.0811,
        "magnitude": 4.1,
        "constellation": "Tuc",
        "importance": 1,
    },
    {
        "id": "NGC 3372",
        "name_en": "Carina Nebula",
        "name_zh": "船底座大星云",
        "object_type": "nebula",
        "ra_deg": 161.2833,
        "dec_deg": -59.8678,
        "magnitude": 1.0,
        "constellation": "Car",
        "importance": 1,
    },
    {
        "id": "M27",
        "name_en": "Dumbbell Nebula",
        "name_zh": "哑铃星云",
        "object_type": "planetary_nebula",
        "ra_deg": 299.9,
        "dec_deg": 22.7211,
        "magnitude": 7.5,
        "constellation": "Vul",
        "importance": 2,
    },
    {
        "id": "M57",
        "name_en": "Ring Nebula",
        "name_zh": "环状星云",
        "object_type": "planetary_nebula",
        "ra_deg": 283.3958,
        "dec_deg": 33.0292,
        "magnitude": 8.8,
        "constellation": "Lyr",
        "importance": 2,
    },
    {
        "id": "M1",
        "name_en": "Crab Nebula",
        "name_zh": "蟹状星云",
        "object_type": "supernova_remnant",
        "ra_deg": 83.633,
        "dec_deg": 22.0145,
        "magnitude": 8.4,
        "constellation": "Tau",
        "importance": 2,
    },
    {
        "id": "M51",
        "name_en": "Whirlpool Galaxy",
        "name_zh": "涡状星系",
        "object_type": "galaxy",
        "ra_deg": 202.4696,
        "dec_deg": 47.1953,
        "magnitude": 8.4,
        "constellation": "CVn",
        "importance": 2,
    },
    {
        "id": "M81",
        "name_en": "Bode's Galaxy",
        "name_zh": "波德星系",
        "object_type": "galaxy",
        "ra_deg": 148.8883,
        "dec_deg": 69.0653,
        "magnitude": 6.9,
        "constellation": "UMa",
        "importance": 2,
    },
    {
        "id": "M82",
        "name_en": "Cigar Galaxy",
        "name_zh": "雪茄星系",
        "object_type": "galaxy",
        "ra_deg": 148.9667,
        "dec_deg": 69.6797,
        "magnitude": 8.4,
        "constellation": "UMa",
        "importance": 2,
    },
    {
        "id": "M101",
        "name_en": "Pinwheel Galaxy",
        "name_zh": "风车星系",
        "object_type": "galaxy",
        "ra_deg": 210.8023,
        "dec_deg": 54.349,
        "magnitude": 7.9,
        "constellation": "UMa",
        "importance": 2,
    },
    {
        "id": "M104",
        "name_en": "Sombrero Galaxy",
        "name_zh": "草帽星系",
        "object_type": "galaxy",
        "ra_deg": 189.9976,
        "dec_deg": -11.6231,
        "magnitude": 8.0,
        "constellation": "Vir",
        "importance": 2,
    },
]


def get_deep_sky_objects() -> List[Dict[str, Any]]:
    return [dict(item) for item in DEEP_SKY_OBJECTS]
